### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by derrickmehaffy** [derrickmehaffy/do-strapi-test#1]
- [ ] Setup Strapi flat file + PostgreSQL (master branch)
- [ ] Setup Strapi Docker + PostgreSQL Docker (docker branch)
- [ ] Test auto starting with watcher using pm2

**Comment by derrickmehaffy** [comment]
Need to rethink how to set the proxy address in the server.json file on initial startup. 🤔
